//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fApp.Games.MusicCounter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MusicCounterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicCounterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fApp.Games.MusicCounter.MusicCounterResources", typeof(MusicCounterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category 1.
        /// </summary>
        public static string Category_1 {
            get {
                return ResourceManager.GetString("Category_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category 2.
        /// </summary>
        public static string Category_2 {
            get {
                return ResourceManager.GetString("Category_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category 3.
        /// </summary>
        public static string Category_3 {
            get {
                return ResourceManager.GetString("Category_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category 4.
        /// </summary>
        public static string Category_4 {
            get {
                return ResourceManager.GetString("Category_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape....
        /// </summary>
        public static string Game_End {
            get {
                return ResourceManager.GetString("Game_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Game_Reset {
            get {
                return ResourceManager.GetString("Game_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 1-1.
        /// </summary>
        public static string Phrase_1_1 {
            get {
                return ResourceManager.GetString("Phrase_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 1-2.
        /// </summary>
        public static string Phrase_1_2 {
            get {
                return ResourceManager.GetString("Phrase_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 1-3.
        /// </summary>
        public static string Phrase_1_3 {
            get {
                return ResourceManager.GetString("Phrase_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 1-4.
        /// </summary>
        public static string Phrase_1_4 {
            get {
                return ResourceManager.GetString("Phrase_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 1-5.
        /// </summary>
        public static string Phrase_1_5 {
            get {
                return ResourceManager.GetString("Phrase_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 1-6.
        /// </summary>
        public static string Phrase_1_6 {
            get {
                return ResourceManager.GetString("Phrase_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 2-1.
        /// </summary>
        public static string Phrase_2_1 {
            get {
                return ResourceManager.GetString("Phrase_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 2-2.
        /// </summary>
        public static string Phrase_2_2 {
            get {
                return ResourceManager.GetString("Phrase_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 2-3.
        /// </summary>
        public static string Phrase_2_3 {
            get {
                return ResourceManager.GetString("Phrase_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 2-4.
        /// </summary>
        public static string Phrase_2_4 {
            get {
                return ResourceManager.GetString("Phrase_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 2-5.
        /// </summary>
        public static string Phrase_2_5 {
            get {
                return ResourceManager.GetString("Phrase_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 2-6.
        /// </summary>
        public static string Phrase_2_6 {
            get {
                return ResourceManager.GetString("Phrase_2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 3-1.
        /// </summary>
        public static string Phrase_3_1 {
            get {
                return ResourceManager.GetString("Phrase_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 3-2.
        /// </summary>
        public static string Phrase_3_2 {
            get {
                return ResourceManager.GetString("Phrase_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 3-3.
        /// </summary>
        public static string Phrase_3_3 {
            get {
                return ResourceManager.GetString("Phrase_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 3-4.
        /// </summary>
        public static string Phrase_3_4 {
            get {
                return ResourceManager.GetString("Phrase_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 3-5.
        /// </summary>
        public static string Phrase_3_5 {
            get {
                return ResourceManager.GetString("Phrase_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 3-6.
        /// </summary>
        public static string Phrase_3_6 {
            get {
                return ResourceManager.GetString("Phrase_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 4-1.
        /// </summary>
        public static string Phrase_4_1 {
            get {
                return ResourceManager.GetString("Phrase_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 4-2.
        /// </summary>
        public static string Phrase_4_2 {
            get {
                return ResourceManager.GetString("Phrase_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 4-3.
        /// </summary>
        public static string Phrase_4_3 {
            get {
                return ResourceManager.GetString("Phrase_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 4-4.
        /// </summary>
        public static string Phrase_4_4 {
            get {
                return ResourceManager.GetString("Phrase_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 4-5.
        /// </summary>
        public static string Phrase_4_5 {
            get {
                return ResourceManager.GetString("Phrase_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase 4-6.
        /// </summary>
        public static string Phrase_4_6 {
            get {
                return ResourceManager.GetString("Phrase_4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string Setup_Go {
            get {
                return ResourceManager.GetString("Setup_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return....
        /// </summary>
        public static string Stats_Back {
            get {
                return ResourceManager.GetString("Stats_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinks.
        /// </summary>
        public static string Stats_Phrases {
            get {
                return ResourceManager.GetString("Stats_Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats:.
        /// </summary>
        public static string Stats_Title {
            get {
                return ResourceManager.GetString("Stats_Title", resourceCulture);
            }
        }
    }
}
