//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fApp.Games.EndureIntervals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EndureIntervalsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndureIntervalsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fApp.Games.EndureIntervals.EndureIntervalsResources", typeof(EndureIntervalsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Game_End {
            get {
                return ResourceManager.GetString("Game_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Game_Pause {
            get {
                return ResourceManager.GetString("Game_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Game_Reset {
            get {
                return ResourceManager.GetString("Game_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Game_Start {
            get {
                return ResourceManager.GetString("Game_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Setup_Enabled {
            get {
                return ResourceManager.GetString("Setup_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string Setup_Go {
            get {
                return ResourceManager.GetString("Setup_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Setup_Max {
            get {
                return ResourceManager.GetString("Setup_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Setup_Min {
            get {
                return ResourceManager.GetString("Setup_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max repeats.
        /// </summary>
        public static string Setup_Repeats {
            get {
                return ResourceManager.GetString("Setup_Repeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer 1.
        /// </summary>
        public static string Setup_Timer1 {
            get {
                return ResourceManager.GetString("Setup_Timer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer 2.
        /// </summary>
        public static string Setup_Timer2 {
            get {
                return ResourceManager.GetString("Setup_Timer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return....
        /// </summary>
        public static string Stats_Back {
            get {
                return ResourceManager.GetString("Stats_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats:.
        /// </summary>
        public static string Stats_Title {
            get {
                return ResourceManager.GetString("Stats_Title", resourceCulture);
            }
        }
    }
}
